export const ADD_CHOREO = "ADD_CHOREO";
export const LOAD_CHOREO = "LOAD_CHOREO";
export const REMOVE_CHOREO = "REMOVE_CHOREO";
export const RENAME_CHOREO = "RENAME_CHOREO";
export const PUBLISH_CHOREO = "PUBLISH_CHOREO";
export const UNPUBLISH_CHOREO = "UNPUBLISH_CHOREO";
export const UPDATE_CHOREO_IMAGE = "UPDATE_CHOREO_IMAGE";
export const UPDATE_CHOREO_MUSIC = "UPDATE_CHOREO_MUSIC";
export const EDIT_STAGE_DIMENSIONS = "EDIT_STAGE_DIMENSIONS";
export const ADD_FORMATION = "ADD_FORMATION";
export const REMOVE_FORMATION = "REMOVE_FORMATION";
export const RENAME_FORMATION = "RENAME_FORMATION";
export const REORDER_FORMATION = "REORDER_FORMATION";
export const EDIT_FORMATION_DURATION = "EDIT_FORMATION_DURATION";
export const EDIT_FORMATION_TRANSITION = "EDIT_FORMATION_TRANSITION";
export const CLEAR_FORMATION_TRANSITION = "CLEAR_FORMATION_TRANSITION";
export const ADD_DANCER = "ADD_DANCER";
export const REMOVE_DANCER = "REMOVE_DANCER";
export const RENAME_DANCER = "RENAME_DANCER";
export const ADD_DANCER_TO_FORMATION = "ADD_DANCER_TO_FORMATION";
export const REMOVE_DANCER_FROM_FORMATION = "REMOVE_DANCER_FROM_FORMATION";
export const MOVE_DANCER = "MOVE_DANCER";
export const CLEAR_TRIAL_CHOREO = "CLEAR_TRIAL_CHOREO";

// UI actions
export const SWITCH_ACTIVE_FORMATION = "SWITCH_ACTIVE_FORMATION";
export const SET_LABELS_VIEW = "SET_LABELS_VIEW";
export const SELECT_DANCER = "SELECT_DANCER";
export const DESELECT_DANCER = "DESELECT_DANCER";
export const CLEAR_DANCER_SELECTION = "CLEAR_DANCER_SELECTION";
export const TIMELINE_JUMP = "TIMELINE_JUMP";
export const TIMELINE_PLAY = "TIMELINE_PLAY";
export const TIMELINE_PAUSE = "TIMELINE_PAUSE";
export const LOAD_ANIMATED_VIEW = "LOAD_ANIMATED_VIEW";
export const UNLOAD_ANIMATED_VIEW = "UNLOAD_ANIMATED_VIEW";
export const SET_PLAYBACK_RATE = "SET_PLAYBACK_RATE";
export const RESET_UI_STATE = "RESET_UI_STATE";

// User auth actions
export const USER_LOGOUT = "USER_LOGOUT";

// Formation History actions
export const UNDO_FORMATION_CHANGE = "UNDO_FORMATION_CHANGE";
export const REDO_FORMATION_CHANGE = "REDO_FORMATION_CHANGE";
export const CLEAR_FORMATION_HISTORY = "CLEAR_FORMATION_HISTORY";

// Dummy action
export const DUMMY_ACTION = "DUMMY_ACTION";