export const ADD_DANCE = "ADD_DANCE";
export const REMOVE_DANCE = "REMOVE_DANCE";
export const RENAME_DANCE = "RENAME_DANCE";
export const EDIT_STAGE_DIMENSIONS = "EDIT_STAGE_DIMENSIONS";
export const ADD_FRAME = "ADD_FRAME";
export const REMOVE_FRAME = "REMOVE_FRAME";
export const RENAME_FRAME = "RENAME_FRAME";
export const EDIT_FRAME_DURATION = "EDIT_FRAME_DURATION";
export const ADD_DANCER = "ADD_DANCER";
export const REMOVE_DANCER = "REMOVE_DANCER";
export const RENAME_DANCER = "RENAME_DANCER";
export const ADD_DANCER_TO_FRAME = "ADD_DANCER_TO_FRAME";
export const REMOVE_DANCER_FROM_FRAME = "REMOVE_DANCER_FROM_FRAME";
export const MOVE_DANCER = "MOVE_DANCER";

export const SWITCH_ACTIVE_DANCE = "SWITCH_ACTIVE_DANCE";
